version: 1
disable_existing_loggers: false
formatters:
  simple:
    (): logger.custom.StdoutCustomFormatter
    fmt_keys:
      format: '%(asctime)s %(levelname)8s %(filename)s:%(funcName)s:%(lineno)3d %(message)s'
      # format: '%(asctime)s %(levelname)8s %(module)s.%(funcName)s:%(lineno)3d %(message)s'
  json:
    (): logger.custom.JSONCustomFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      pathname: pathname
      line: lineno
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/my_app.log.jsonl
    maxBytes: 1_000_000
    backupCount: 3
loggers:
  root:
    level: INFO
    handlers:
    - stdout
    - file
