version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s | %(levelname)8s | %(filename)s:%(lineno)3d | %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  custom:
    (): logger.custom.StdoutCustomFormatter
    fmt_keys:
      format: "%(asctime)s | %(levelname)8s | %(filename)s:%(lineno)3d | %(message)s"
      datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: custom
    stream: ext://sys.stdout
    level: DEBUG
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: "tests.log"
    level: DEBUG
    maxBytes: 10000000
    backupCount: 5
loggers:
  root:
    level: INFO
    handlers:
    - stdout
    - file
